name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t sonarqube-setup .
    - name: Push Docker image to registry
      run: docker push sonarqube-setup
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: python -m unittest discover
    - name: Run acceptance tests
      run: python -m unittest acceptance_tests
